=== apprensemble/projet_fil_rouge_2015/xml/bookmark.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Moulin (UTC) -->
<!-- entity -->
<!ENTITY % urltype "url">
<!-- root element  -->
<!ELEMENT bookmark (moteur, anglais, voyage, langage)>
<!ELEMENT moteur (%urltype;)+>
<!ELEMENT anglais (%urltype;)+>
<!ELEMENT voyage (avion)>
<!ELEMENT langage (java, html)>
<!ELEMENT avion (%urltype;)+>
<!ELEMENT java (%urltype;)+>
<!ELEMENT html (%urltype;)+>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url
	keyname ID #REQUIRED
>

=== apprensemble/projet_fil_rouge_2015/xml/bookmark.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmark SYSTEM "bookmark.dtd">
<?xml-stylesheet type = "text/xsl" href = "bookmark.xsl" ?>
<!-- file preferiti.xml -->  
<bookmark>
	<moteur>
		<url keyname = "google">http://www.google.com/</url>
	</moteur>
	<anglais>
		<url keyname = "dizionario">http://www.yourdictionary.com/</url>
	</anglais>
	<voyage>
		<avion>
			<url keyname = "alitalia">http://www.alitalia.it/index.html</url>
			<url keyname = "volare">http://www.volare-airlines.com/home/index.asp</url>
		</avion>
	</voyage>
	<langage>
		<java>
			<url keyname = "api1.2">http://java.sun.com/products/jdk/1.2/docs/api/</url>
			<url keyname = "jaxm">http://java.sun.com/xml/jaxm/index.html</url>
		</java>
		<html>
			<url keyname = "ncsa">http://archive.ncsa.uiuc.edu/General/Internet/WWW/HTMLPrimer.html</url>
		</html>
	</langage>
</bookmark>
